### ISSUE TITLE
No target networks in the implementation

### ISSUE THREAD

**Issue by filipolszewski** [songrotek/DDPG#16]
Editing the previous issue as the initial one was an misunderstanding from my side.

Hi,

I see that there are no target networks used in the implementations. Is this even considered while talking about DDPG? I though this is one of the required features.

**Comment by filipolszewski** [comment]
I now see that there are no target networks here! Is this even considered while talking about DDPG? I though this is one of the required features.

**Comment by j314erre** [comment]
Why do you say there are no target networks?  Target networks are created in `CriticNetwork.create_target_q_network()` and `ActorNetwork.create_target_network()`. Then they are used in DPPG.train() to generate values for `next_action_batch` `q_value_batch` and then target networks are updated at end of that method. You should close this issue.
